
tab_numbers: 
  "Стариков Сергей Владимирович": "02"

user_info_path: "data/user_info.json"
weather_journal_path: "data/weather_journal.json"
app_settings_path: "data/app_settings.json"
protocol_times_path: "data/protocol_times.json"
protocols_path: "data/protocols"

# Excel settings
EXCEL_VISIBLE: true
EXCEL_DISPLAY_ALERTS: false

temperatures:
  min: 20
  max: 25
pressure:
  min: 98.5
  max: 102
humdity:
  min: 42
  max: 58

# Счетччики воды
water_meter_good_msg: На основании результатов поверки СИ соответствует установленным метрологическим и техническим требованиям и пригодно к применению.
water_meter_bad_msg: На основании результатов поверки СИ не соответствует установленным метрологическим и техническим требованиям и не пригодно к применению.
water_meter_templates_path: "data/water_meter_templates"
hot_water_temperatures:
  min: 40
  max: 90
cold_water_temperatures:
  min: 5
  max: 15
flow_ranges:
  min: 0.5
  max: 0.95